package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CommsLog generated by hbm2java
 */
public class CommsLog  implements java.io.Serializable {


     private Integer id;
     private FieldReport fieldReport;
     private ResourceType resourceType;
     private Date reportTime;
     private String result;
     private int returnCode;

    public CommsLog() {
    }

	
    public CommsLog(FieldReport fieldReport, ResourceType resourceType, Date reportTime, int returnCode) {
        this.fieldReport = fieldReport;
        this.resourceType = resourceType;
        this.reportTime = reportTime;
        this.returnCode = returnCode;
    }
    public CommsLog(FieldReport fieldReport, ResourceType resourceType, Date reportTime, String result, int returnCode) {
       this.fieldReport = fieldReport;
       this.resourceType = resourceType;
       this.reportTime = reportTime;
       this.result = result;
       this.returnCode = returnCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FieldReport getFieldReport() {
        return this.fieldReport;
    }
    
    public void setFieldReport(FieldReport fieldReport) {
        this.fieldReport = fieldReport;
    }
    public ResourceType getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }
    public Date getReportTime() {
        return this.reportTime;
    }
    
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public int getReturnCode() {
        return this.returnCode;
    }
    
    public void setReturnCode(int returnCode) {
        this.returnCode = returnCode;
    }




}


