/**
 * OpenEyes
 *
 * (C) Moorfields Eye Hospital NHS Foundation Trust, 2008-2011
 * (C) OpenEyes Foundation, 2011-2013
 * This file is part of OpenEyes.
 * OpenEyes is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * OpenEyes is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with OpenEyes in a file titled COPYING. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package OpenEyes
 * @link http://www.openeyes.org.uk
 * @author OpenEyes <info@openeyes.org.uk>
 * @copyright Copyright (c) 2008-2011, Moorfields Eye Hospital NHS Foundation Trust
 * @copyright Copyright (c) 2011-2013, OpenEyes Foundation
 * @license http://www.gnu.org/licenses/gpl-3.0.html The GNU General Public License V3.0
 */
package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CommsLog generated by hbm2java
 */
public class CommsLog  implements java.io.Serializable {


     private Integer id;
     private FieldReport fieldReport;
     private ResourceType resourceType;
     private Date reportTime;
     private String result;
     private int returnCode;

    public CommsLog() {
    }

	
    public CommsLog(FieldReport fieldReport, ResourceType resourceType, Date reportTime, int returnCode) {
        this.fieldReport = fieldReport;
        this.resourceType = resourceType;
        this.reportTime = reportTime;
        this.returnCode = returnCode;
    }
    public CommsLog(FieldReport fieldReport, ResourceType resourceType, Date reportTime, String result, int returnCode) {
       this.fieldReport = fieldReport;
       this.resourceType = resourceType;
       this.reportTime = reportTime;
       this.result = result;
       this.returnCode = returnCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FieldReport getFieldReport() {
        return this.fieldReport;
    }
    
    public void setFieldReport(FieldReport fieldReport) {
        this.fieldReport = fieldReport;
    }
    public ResourceType getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(ResourceType resourceType) {
        this.resourceType = resourceType;
    }
    public Date getReportTime() {
        return this.reportTime;
    }
    
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public int getReturnCode() {
        return this.returnCode;
    }
    
    public void setReturnCode(int returnCode) {
        this.returnCode = returnCode;
    }




}


