package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Directory generated by hbm2java
 */
public class Directory  implements java.io.Serializable {


     private Integer id;
     private String dirPath;
     private Set<Duplicate> duplicates = new HashSet<Duplicate>(0);
     private Set<FieldReport> fieldReports = new HashSet<FieldReport>(0);

    public Directory() {
    }

	
    public Directory(String dirPath) {
        this.dirPath = dirPath;
    }
    public Directory(String dirPath, Set<Duplicate> duplicates, Set<FieldReport> fieldReports) {
       this.dirPath = dirPath;
       this.duplicates = duplicates;
       this.fieldReports = fieldReports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDirPath() {
        return this.dirPath;
    }
    
    public void setDirPath(String dirPath) {
        this.dirPath = dirPath;
    }
    public Set<Duplicate> getDuplicates() {
        return this.duplicates;
    }
    
    public void setDuplicates(Set<Duplicate> duplicates) {
        this.duplicates = duplicates;
    }
    public Set<FieldReport> getFieldReports() {
        return this.fieldReports;
    }
    
    public void setFieldReports(Set<FieldReport> fieldReports) {
        this.fieldReports = fieldReports;
    }




}


