package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA



/**
 * Duplicate generated by hbm2java
 */
public class Duplicate  implements java.io.Serializable {


     private Integer id;
     private Directory directory;
     private String fileName;
     private String sysTime;

    public Duplicate() {
    }

	
    public Duplicate(String sysTime) {
        this.sysTime = sysTime;
    }
    public Duplicate(Directory directory, String fileName, String sysTime) {
       this.directory = directory;
       this.fileName = fileName;
       this.sysTime = sysTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Directory getDirectory() {
        return this.directory;
    }
    
    public void setDirectory(Directory directory) {
        this.directory = directory;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getSysTime() {
        return this.sysTime;
    }
    
    public void setSysTime(String sysTime) {
        this.sysTime = sysTime;
    }




}


