package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FieldError generated by hbm2java
 */
public class FieldError  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set<FieldErrorReport> fieldErrorReports = new HashSet<FieldErrorReport>(0);

    public FieldError() {
    }

    public FieldError(String description, Set<FieldErrorReport> fieldErrorReports) {
       this.description = description;
       this.fieldErrorReports = fieldErrorReports;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<FieldErrorReport> getFieldErrorReports() {
        return this.fieldErrorReports;
    }
    
    public void setFieldErrorReports(Set<FieldErrorReport> fieldErrorReports) {
        this.fieldErrorReports = fieldErrorReports;
    }




}


