package uk.org.openeyes.diagnostics.db;
// Generated 28-Feb-2014 14:23:53 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ResourceType generated by hbm2java
 */
public class ResourceType  implements java.io.Serializable {


     private Integer id;
     private String resourceName;
     private Set<CommsLog> commsLogs = new HashSet<CommsLog>(0);

    public ResourceType() {
    }

	
    public ResourceType(String resourceName) {
        this.resourceName = resourceName;
    }
    public ResourceType(String resourceName, Set<CommsLog> commsLogs) {
       this.resourceName = resourceName;
       this.commsLogs = commsLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }
    public Set<CommsLog> getCommsLogs() {
        return this.commsLogs;
    }
    
    public void setCommsLogs(Set<CommsLog> commsLogs) {
        this.commsLogs = commsLogs;
    }




}


